### PR TITLE
feat: add license, contributing and notice files

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

Add license, notice and contributing files to the repo

## Issues

https://github.com/eclipse-tractusx/eclipse-tractusx.github.io.largefiles/issues/16

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by danielmiehle** [comment]
@AngelikaWittek can you please also check whether the documents are correct. Thank you!

**Review by AngelikaWittek — COMMENTED** [review]
@danielmiehle  Please also add the missing legal doc files:

- LICENSE (Apache-2.0)
- SECURITY.md
- CODE_OF_CONDUCT.md

**Comment by manojava-gk** [comment]
@AngelikaWittek added. Kindly check

**Review by AngelikaWittek — COMMENTED** [review]
Looks good to me.

**Review by danielmiehle — APPROVED** [review]

**Comment by danielmiehle** [comment]
@manojava-gk : Thank you for preparing the PR!

**Pull request merged**
