### PR TITLE
docs(presentations): add extension for .pdf files and first slides

### PR DESCRIPTION
**Pull request by stephanbcbauer**
## Description

This PR adds the first presentation for our refinement day 1

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by tom-rm-meyer-ISST** [comment]
@stephanbcbauer I'm wondering if it makes sense to put a license file next to the presentation similar as for images?

**Comment by stephanbcbauer** [comment]
> @stephanbcbauer I'm wondering if it makes sense to put a license file next to the presentation similar as for images?

Wood be Fine for me. Would it be a contribution done by eclipse? Or by the catena-X association?

**Comment by stephanbcbauer** [comment]
> > @stephanbcbauer I'm wondering if it makes sense to put a license file next to the presentation similar as for images?
> 
> Wood be Fine for me. Would it be a contribution done by eclipse? Or by the catena-X association?

let's have a [look.](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io.largefiles/commit/a68bc1ba671d03e3368181010fc24de4e86fa90b)

**Comment by stephanbcbauer** [comment]
And I am still wondering if R25.03 at the beginning of the filename would make more sense because of sorting :)

**Comment by tom-rm-meyer-ISST** [comment]
> > @stephanbcbauer I'm wondering if it makes sense to put a license file next to the presentation similar as for images?
> 
> Wood be Fine for me. Would it be a contribution done by eclipse? Or by the catena-X association?

Makes sense that you put the association in there. Works also without.

>And I am still wondering if R25.04 at the beginning of the filename would make more sense because of sorting :)

Yes likely!

**Comment by stephanbcbauer** [comment]
> > > > @stephanbcbauer I'm wondering if it makes sense to put a license file next to the presentation similar as for images?
> > > 
> > > 
> > > Wood be Fine for me. Would it be a contribution done by eclipse? Or by the catena-X association?
> > 
> > 
> > Makes sense that you put the association in there. Works also without.
> > > And I am still wondering if R25.04 at the beginning of the filename would make more sense because of sorting :)
> > 
> > 
> > Yes likely!
> 
> Then I think we are good to go/merge ;)

One approval would be cool, even if it is not needed :)

**Review by tom-rm-meyer-ISST — APPROVED** [review]
LGTM

**Pull request merged**
